# Generated by Django 5.0.2 on 2024-03-14 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="dwelling_count",
        ),
    ]
