# Generated by Django 5.0.2 on 2024-03-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_place_created_at_place_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="member_count",
        ),
        migrations.AlterField(
            model_name="place",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
    ]
