name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/huron.key
        chmod 600 ~/.ssh/huron.key
        cat >> ~/.ssh/config << EOF
        Host huron
          HostName treehouselondon.org
          User root
          IdentityFile ~/.ssh/huron.key
          StrictHostKeyChecking no
        EOF
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}

    - name: Install ansible
      run: pip install ansible==9.3.0

    - name: Run ansible
      run: cd ansible/ && ansible-playbook playbook.yaml
      env:
        ANSIBLE_HOST: ${{ env.ANSIBLE_HOST }}
        ANSIBLE_USER: ${{ env.ANSIBLE_USER }}
        DEBUG: ${{ env.DEBUG }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
